import type { Metadata } from "next";

import Header from "@/components/molecules/Header";
import styles from "./layout/layout.module.css"

import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <div className={styles.wrapper}>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
